Increased maximum excel size to 60MB
Los-Crackitos/Excelante pull request #46
Opened 2021-05-28 15:39 UTC by kaleween

2021-05-30 22:05 UTC, Jerome1337 requested changes

2021-05-30 22:05 UTC, Jerome1337 commented on handlers/reader.go
> +	r.ParseMultipartForm(60)
should be `60 << 20` (means 60mb)

2021-05-30 22:05 UTC, Jerome1337 commented on handlers/reader.go
> +	r.ParseMultipartForm(60)
should be `60 << 20` (means 60mb)

2021-05-31 07:34 UTC, kaleween commented on handlers/reader.go
> +	r.ParseMultipartForm(60)
done

2021-05-31 07:34 UTC, kaleween commented on handlers/reader.go
> +	r.ParseMultipartForm(60)
done

2021-05-31 09:16 UTC, Thyrael approved these changes

2021-05-31 09:17 UTC, Jerome1337 approved these changes

2021-05-31 09:56 UTC, Jerome1337 commented
Closed in favor of #47

2021-05-31 09:56 UTC, closed without merging